Multi carrier
myparcelbe/api pull request #6
Opened 2019-07-09 09:40 UTC by RichardPerdaan

2019-07-15 14:09 UTC, reindert-vetter requested changes

2019-07-15 14:09 UTC, reindert-vetter commented on index.html
> +        "reference_identifier": "DPD shipment"
```suggestion
        "reference_identifier": "Order 123456"
```

2019-07-15 14:09 UTC, reindert-vetter commented on index.html
> +        "reference_identifier": "bpost pickup"
```suggestion
        "reference_identifier": "order-012356"
```

2019-07-17 13:23 UTC, RichardPerdaan commented on index.html
> +        "reference_identifier": "bpost pickup"
Done

2019-07-17 13:23 UTC, RichardPerdaan commented on index.html
> +        "reference_identifier": "DPD shipment"
Done

2019-07-17 13:23 UTC, merged